/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author w1606044
 */
public class digital_timer extends javax.swing.JFrame {
    int seconds1 = 1;
         int seconds2 = 1;
         int minutes1 = 1;
         int minutes2 = 1;

    /**
     * Creates new form digital_timer
     */
    public digital_timer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        numArray1 = new javax.swing.JTextField();
        numArray2 = new javax.swing.JTextField();
        numArray3 = new javax.swing.JTextField();
        numArray7 = new javax.swing.JTextField();
        numArray5 = new javax.swing.JTextField();
        numArray6 = new javax.swing.JTextField();
        numArray4 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        startTimer = new javax.swing.JButton();
        displayBtn1 = new javax.swing.JButton();
        timeMins = new javax.swing.JButton();
        plusOne = new javax.swing.JButton();
        digitNum1 = new javax.swing.JTextField();
        digitNum6 = new javax.swing.JTextField();
        digitNum7 = new javax.swing.JTextField();
        digitNum5 = new javax.swing.JTextField();
        displayBtn5 = new javax.swing.JButton();
        digitNum4 = new javax.swing.JTextField();
        displayBtn4 = new javax.swing.JButton();
        digitNum3 = new javax.swing.JTextField();
        displayBtn3 = new javax.swing.JButton();
        digitNum2 = new javax.swing.JTextField();
        displayBtn2 = new javax.swing.JButton();
        stopTimer = new javax.swing.JButton();
        img4 = new javax.swing.JLabel();
        img2 = new javax.swing.JLabel();
        img3 = new javax.swing.JLabel();
        img1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        numArray1.setEditable(false);
        numArray1.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(numArray1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 70, 20));

        numArray2.setEditable(false);
        numArray2.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(numArray2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, 20, 50));

        numArray3.setEditable(false);
        numArray3.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(numArray3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 40, 20, 50));

        numArray7.setEditable(false);
        numArray7.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(numArray7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, 70, 20));

        numArray5.setEditable(false);
        numArray5.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(numArray5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 20, 50));

        numArray6.setEditable(false);
        numArray6.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(numArray6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, 20, 50));

        numArray4.setEditable(false);
        numArray4.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(numArray4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, 70, 20));

        jLabel1.setFont(new java.awt.Font("Stencil", 0, 48)); // NOI18N
        jLabel1.setText("Digital Timer");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 400, 50));

        jLabel2.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        jLabel2.setText("By Camal Aleksandersen ( W1606044 )");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel4.setText("One Second(s)");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 210, -1, -1));

        jLabel5.setText("One Minute(s)");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, -1, -1));

        jLabel7.setText("Digit");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, -1, -1));

        jLabel10.setText("Ten Minute(s)");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, -1, -1));

        jLabel6.setText("Stopping Point (Seconds)");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, -1, 20));

        jLabel8.setText("Ten Second(s)");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, -1, -1));

        startTimer.setText("(+) START");
        startTimer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                startTimerMouseClicked(evt);
            }
        });
        getContentPane().add(startTimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 130, 90, -1));

        displayBtn1.setText("Display Digit");
        displayBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                displayBtn1MouseClicked(evt);
            }
        });
        displayBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayBtn1ActionPerformed(evt);
            }
        });
        getContentPane().add(displayBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(569, 50, -1, -1));

        timeMins.setText("Time in Minutes");
        getContentPane().add(timeMins, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 450, 110, 20));

        plusOne.setText("( +1 )");
        plusOne.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                plusOneMouseClicked(evt);
            }
        });
        getContentPane().add(plusOne, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 80, 90, -1));

        digitNum1.setText("0");
        getContentPane().add(digitNum1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 20, 50, -1));

        digitNum6.setText("0");
        getContentPane().add(digitNum6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 450, 90, -1));

        digitNum7.setText("0");
        getContentPane().add(digitNum7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 110, 20));

        digitNum5.setText("0");
        getContentPane().add(digitNum5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, 50, 20));

        displayBtn5.setText("Display Digit");
        displayBtn5.setActionCommand("");
        getContentPane().add(displayBtn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, 100, 30));

        digitNum4.setText("0");
        getContentPane().add(digitNum4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, 50, 20));

        displayBtn4.setText("Display Digit");
        displayBtn4.setActionCommand("");
        getContentPane().add(displayBtn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 400, 100, 30));

        digitNum3.setText("0");
        getContentPane().add(digitNum3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 370, 50, 20));

        displayBtn3.setText("Display Digit");
        displayBtn3.setActionCommand("");
        getContentPane().add(displayBtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 400, 100, 30));

        digitNum2.setText("0");
        getContentPane().add(digitNum2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 370, 50, 20));

        displayBtn2.setText("Display Digit");
        displayBtn2.setActionCommand("");
        getContentPane().add(displayBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 400, 100, 30));

        stopTimer.setText("(-) STOP");
        getContentPane().add(stopTimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 160, 90, -1));

        img4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Number Images/0.png"))); // NOI18N
        img4.setText("jLabel1");
        getContentPane().add(img4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 120, 130));

        img2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Number Images/0.png"))); // NOI18N
        img2.setText("jLabel1");
        getContentPane().add(img2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 120, 130));

        img3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Number Images/0.png"))); // NOI18N
        img3.setText("jLabel1");
        getContentPane().add(img3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 120, 130));

        img1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Number Images/0.png"))); // NOI18N
        img1.setText("jLabel1");
        getContentPane().add(img1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, 120, 130));

        pack();
    }// </editor-fold>                        

    private void displayBtn1ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void displayBtn1MouseClicked(java.awt.event.MouseEvent evt) {                                         
        //Changing the value of the DIGIT
        int value = Integer.parseInt(digitNum1.getText());
        //Value = 0
        if(value == 0){
            numArray1.setVisible(true);
            numArray2.setVisible(true);
            numArray3.setVisible(true);
            numArray4.setVisible(false);
            numArray5.setVisible(true);
            numArray6.setVisible(true);
            numArray7.setVisible(true);
        }else if(value == 1){
            numArray1.setVisible(false);
            numArray2.setVisible(false);
            numArray3.setVisible(true);
            numArray4.setVisible(false);
            numArray5.setVisible(false);
            numArray6.setVisible(true);
            numArray7.setVisible(false);
        }else if(value == 2){
            numArray1.setVisible(true);
            numArray2.setVisible(false);
            numArray3.setVisible(true);
            numArray4.setVisible(true);
            numArray5.setVisible(true);
            numArray6.setVisible(false);
            numArray7.setVisible(true);
        }else if(value == 3){
            numArray1.setVisible(true);
            numArray2.setVisible(false);
            numArray3.setVisible(true);
            numArray4.setVisible(true);
            numArray5.setVisible(false);
            numArray6.setVisible(true);
            numArray7.setVisible(true);
        }else if(value == 4){
            numArray1.setVisible(false);
            numArray2.setVisible(true);
            numArray3.setVisible(true);
            numArray4.setVisible(true);
            numArray5.setVisible(false);
            numArray6.setVisible(true);
            numArray7.setVisible(false);
        }else if(value == 5){
            numArray1.setVisible(true);
            numArray2.setVisible(true);
            numArray3.setVisible(false);
            numArray4.setVisible(true);
            numArray5.setVisible(false);
            numArray6.setVisible(true);
            numArray7.setVisible(true);
        }else if(value == 6){
            numArray1.setVisible(true);
            numArray2.setVisible(true);
            numArray3.setVisible(false);
            numArray4.setVisible(true);
            numArray5.setVisible(true);
            numArray6.setVisible(true);
            numArray7.setVisible(true);
        }else if(value == 7){
            numArray1.setVisible(true);
            numArray2.setVisible(false);
            numArray3.setVisible(true);
            numArray4.setVisible(false);
            numArray5.setVisible(false);
            numArray6.setVisible(true);
            numArray7.setVisible(false);
        }else if(value == 8){
            numArray1.setVisible(true);
            numArray2.setVisible(true);
            numArray3.setVisible(true);
            numArray4.setVisible(true);
            numArray5.setVisible(true);
            numArray6.setVisible(true);
            numArray7.setVisible(true);
        }else if(value == 9){
            numArray1.setVisible(true);
            numArray2.setVisible(true);
            numArray3.setVisible(true);
            numArray4.setVisible(true);
            numArray5.setVisible(false);
            numArray6.setVisible(true);
            numArray7.setVisible(true);
        }
    }                                        

    private void plusOneMouseClicked(java.awt.event.MouseEvent evt) {                                     
         int value = Integer.parseInt(digitNum1.getText());
         digital_timer dt = new digital_timer();
         int s1 = dt.seconds1;
         int s2 = dt.seconds1;
         int m1 = dt.minutes1;
         int m2 = dt.minutes2;
         
         value+=1;
         if(value >= 9){
             digitNum1.setText("0");
            System.out.println(s1);
            img1.setIcon(new javax.swing.ImageIcon("src/Number Images/"+s1+".png"));
            dt.seconds1 += 1;
            
         }else{
            String valueToString = Integer.toString(value);
            digitNum1.setText(valueToString);
         }
    }                                    
         
    private void startTimerMouseClicked(java.awt.event.MouseEvent evt) {                                        
        return;
    }                                       

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(digital_timer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(digital_timer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(digital_timer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(digital_timer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new digital_timer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JTextField digitNum1;
    private javax.swing.JTextField digitNum2;
    private javax.swing.JTextField digitNum3;
    private javax.swing.JTextField digitNum4;
    private javax.swing.JTextField digitNum5;
    private javax.swing.JTextField digitNum6;
    private javax.swing.JTextField digitNum7;
    private javax.swing.JButton displayBtn1;
    private javax.swing.JButton displayBtn2;
    private javax.swing.JButton displayBtn3;
    private javax.swing.JButton displayBtn4;
    private javax.swing.JButton displayBtn5;
    private javax.swing.JLabel img1;
    private javax.swing.JLabel img2;
    private javax.swing.JLabel img3;
    private javax.swing.JLabel img4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField numArray1;
    private javax.swing.JTextField numArray2;
    private javax.swing.JTextField numArray3;
    private javax.swing.JTextField numArray4;
    private javax.swing.JTextField numArray5;
    private javax.swing.JTextField numArray6;
    private javax.swing.JTextField numArray7;
    private javax.swing.JButton plusOne;
    private javax.swing.JButton startTimer;
    private javax.swing.JButton stopTimer;
    private javax.swing.JButton timeMins;
    // End of variables declaration                   
}
